name: Run Polyspace analysis on PR
on: [push]
jobs:
  my-job:
    name: Run analysis
    runs-on: self-hosted

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Generate compilation database
      uses: cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON .
    - name: Analyze pull request
      uses: polyspace-actions/polyspace-bug-finder@24.2.0
      with:
        compilation-database-file: compile_commands.json
        checkers-file: checkers.xml
        sarif-file: results.sarif

    - name: Annotate the findings to the commit
      uses: polyspace-actions/polyspace-findings@24.2.0
      with:
        sarif-file: results.sarif